#!/usr/bin/env bash

echo 'Go-getting and update plugins'
go get -u github.com/aburgd/plugins/...
echo 'Updating the plugins subdir with godep'
godep update github.com/aburgd/plugins/...
echo 'Save the plugins subdir'
godep save ./...
